services:
  app:
    container_name: angular_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4300:80'
    environment:
      - API_URL=http://cars.cprogroup.ru/api/rubetek/angular-testcase-list/
    volumes:
      - .:/app
